export const FETCH_TOURNAMENTS_START = 'FETCH_TOURNAMENTS_START';
export const FETCH_TOURNAMENTS_SUCCESS = 'FETCH_TOURNAMENTS_SUCCESS';
export const FETCH_TOURNAMENTS_FAIL = 'FETCH_TOURNAMENTS_FAIL';
export const SET_SEARCH = 'SET_SEARCH';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const UPDATE_TOURNAMENT = 'UPDATE_TOURNAMENT';
export const SET_TOURNAMENTS = 'SET_TOURNAMENTS';
