export const FETCH_TOURNAMENTS_START = 'FETCH_TOURNAMENTS_START';
export const FETCH_TOURNAMENTS_SUCCESS = 'FETCH_TOURNAMENTS_SUCCESS';
export const FETCH_TOURNAMENTS_FAIL = 'FETCH_TOURNAMENTS_FAIL';
